### ISSUE TITLE
Error: yii\i18n\PhpMessageSource::loadFallbackMessages

### ISSUE THREAD

**Issue by celsoft** [lavrentiev/yii2-toastr#5]
Дебагер валит ошибку.

The message file for category 'app' does not exist: /home/*****_/www/messages/ru-RU/app.php Fallback file does not exist as well: /home/**_**_/www/messages/ru/app.php
/home/**_**_/www/vendor/lavrentiev/yii2-toastr/src/Notification.php (49)
/home/**_**_/www/widgets/Alert.php (13)
/home/**_***/www/views/layouts/main.php (14)

**Comment by lavrentiev** [comment]
Хорошо спасибо, а так это обозначает, что ты не используешь i18n или нету нужной категории.

**Comment by celsoft** [comment]
Проект простой и там не нужна мультиязычность. Поэтому и заметил)

**Comment by lavrentiev** [comment]
@celsoft в ближайшее время поправляю.

**Comment by celsoft** [comment]
спасибо.
